### ISSUE TITLE
extra space appended

### ISSUE THREAD

**Issue by raviteja83** [ismarslomic/angular-read-more#26]
if a word is broken while showing less text an extra space gets added after that character when full text is shown.

 out **t ...** Read more on expand becomes **t  hese** collection. An extra space gets added after t

**Comment by BexAstley** [comment]
yes have also noticed this, space in between a full word.  it will fail our QA. Any solution to this/tips on how to get round it with css or something?

**Comment by omarsafwany** [comment]
@ismarslomic Any updates regarding this issue?

**Comment by ismarslomic** [comment]
@raviteja83 @BexAstley @omarsafwany : sorry for late response! Reason why the extra whitespace is added between last character and "..." is because we are using multiple spans, and default behaviour in HTML is to add an extra whitespace between spans. You might override this by using CSS for span element. Im closing this issue for now.

**Comment by ismarslomic** [comment]
Actually I got this fixed in 4660d51725099dbc6bca7b5103f5128fa9ae9c5d
